/* @flow */
import type {
  LOAD_DATA_INITIATION_TYPE,
  LOAD_DATA_SUCCESS_TYPE,
  LOAD_DATA_FAILURE_TYPE,
  CLEAR_ERRORS_TYPE
} from './flowTypes';
export const LOAD_DATA_INITIATION: LOAD_DATA_INITIATION_TYPE = 'POSTFEEDPAGE/LOAD_DATA_INITIATION';
export const LOAD_DATA_SUCCESS: LOAD_DATA_SUCCESS_TYPE = 'POSTFEEDPAGE/LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE: LOAD_DATA_FAILURE_TYPE = 'POSTFEEDPAGE/LOAD_DATA_FAILURE';
export const CLEAR_ERRORS: CLEAR_ERRORS_TYPE = 'POSTFEEDPAGE/CLEAR_ERRORS';
