export const REQUEST_INITIATION = 'PAGE_TYPES/REQUEST_INITIATION';
export const REQUEST_FAILURE = 'PAGE_TYPES/REQUEST_FAILURE';

export const LOAD_DATA_SUCCESS = 'PAGE_TYPES/LOAD_DATA_SUCCESS';
export const DELETE_SUCCESS = 'PAGE_TYPES/DELETE_SUCCESS';
export const GET_PAGE_TYPE_SUCCESS = 'PAGE_TYPES/GET_PAGE_TYPE_SUCCESS';
export const CONFIRM_DELETION = 'PAGE_TYPES/CONFIRM_DELETION';
export const CANCEL_DELETION = 'PAGE_TYPES/CANCEL_DELETION';

export const FORM_INPUT = 'PAGE_TYPES/FORM_INPUT';
export const CLEAR_FORM = 'PAGE_TYPES/CLEAR_FORM';
export const SUBMISSION_SUCCESS = 'PAGE_TYPES/SUBMISSION_SUCCESS';
export const CLEAR_ERROR = 'PAGE_TYPES/CLEAR_ERROR';

export const REORDER_PAGE_TYPE = 'PAGE_TYPES/REORDER_PAGE_TYPE';
