export const POSTS_REQUEST = 'POSTS_REQUEST';
export const POSTS_ERROR = 'POSTS_ERROR';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POSTS_SUCCESS = 'POSTS_SUCCESS';
export const POSTS_DELETE_SUCCESS = 'POSTS_DELETE_SUCCESS';
export const SET_POST = 'SET_POST';

export const POST_DELETE_SECTION = 'POST_DELETE_SECTION';
export const POST_MOVE_UP_SECTION = 'POST_MOVE_UP_SECTION';
export const POST_MOVE_DOWN_SECTION = 'POST_MOVE_DOWN_SECTION';
export const POST_ADD_SECTION = 'POST_ADD_SECTION';
export const POST_CLEAR_ERROR = 'POST_CLEAR_ERROR';
export const POST_EDIT_SECTION = 'POST_EDIT_SECTION';

export const POST_SET_CONTENT_BLOCKS = 'POST_SET_CONTENT_BLOCKS';
export const POST_REMOVE_UNUSED_CONTENT_BLOCKS = 'POST_REMOVE_UNUSED_CONTENT_BLOCKS';
export const POST_DUPLICATE_SECTION = 'POST_DUPLICATE_SECTION';
