export const DASHBOARD_HOME_PAGE_REQUEST = 'DASHBOARD_HOME_PAGE_REQUEST';
export const DASHBOARD_HOME_PAGE_ERROR = 'DASHBOARD_HOME_PAGE_ERROR';
export const DASHBOARD_HOME_PAGE_SUCCESS = 'DASHBOARD_HOME_PAGE_SUCCESS';
