// flow-typed signature: 7d3915af6d9b5be96e4e4bfb1a315cbe
// flow-typed version: <<STUB>>/apicache_v^0.8.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apicache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'apicache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apicache/src/apicache' {
  declare module.exports: any;
}

declare module 'apicache/src/memory-cache' {
  declare module.exports: any;
}

declare module 'apicache/test/api/express-gzip' {
  declare module.exports: any;
}

declare module 'apicache/test/api/express' {
  declare module.exports: any;
}

declare module 'apicache/test/api/lib/routes' {
  declare module.exports: any;
}

declare module 'apicache/test/api/restify-gzip' {
  declare module.exports: any;
}

declare module 'apicache/test/api/restify' {
  declare module.exports: any;
}

declare module 'apicache/test/apicache_test' {
  declare module.exports: any;
}

declare module 'apicache/test/mock_api_gzip_restify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apicache/src/apicache.js' {
  declare module.exports: $Exports<'apicache/src/apicache'>;
}
declare module 'apicache/src/memory-cache.js' {
  declare module.exports: $Exports<'apicache/src/memory-cache'>;
}
declare module 'apicache/test/api/express-gzip.js' {
  declare module.exports: $Exports<'apicache/test/api/express-gzip'>;
}
declare module 'apicache/test/api/express.js' {
  declare module.exports: $Exports<'apicache/test/api/express'>;
}
declare module 'apicache/test/api/lib/routes.js' {
  declare module.exports: $Exports<'apicache/test/api/lib/routes'>;
}
declare module 'apicache/test/api/restify-gzip.js' {
  declare module.exports: $Exports<'apicache/test/api/restify-gzip'>;
}
declare module 'apicache/test/api/restify.js' {
  declare module.exports: $Exports<'apicache/test/api/restify'>;
}
declare module 'apicache/test/apicache_test.js' {
  declare module.exports: $Exports<'apicache/test/apicache_test'>;
}
declare module 'apicache/test/mock_api_gzip_restify.js' {
  declare module.exports: $Exports<'apicache/test/mock_api_gzip_restify'>;
}
