// flow-typed signature: 9bf7060df2a7fa8520e650b0b14cf97e
// flow-typed version: <<STUB>>/clone-stats_v0.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clone-stats'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'clone-stats' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clone-stats/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clone-stats/index' {
  declare module.exports: $Exports<'clone-stats'>;
}
declare module 'clone-stats/index.js' {
  declare module.exports: $Exports<'clone-stats'>;
}
declare module 'clone-stats/test.js' {
  declare module.exports: $Exports<'clone-stats/test'>;
}
