// flow-typed signature: 46427e947197267e3d2d2b2615bbe719
// flow-typed version: <<STUB>>/color-convert_v^1.9.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color-convert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'color-convert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'color-convert/conversions' {
  declare module.exports: any;
}

declare module 'color-convert/route' {
  declare module.exports: any;
}

// Filename aliases
declare module 'color-convert/conversions.js' {
  declare module.exports: $Exports<'color-convert/conversions'>;
}
declare module 'color-convert/index' {
  declare module.exports: $Exports<'color-convert'>;
}
declare module 'color-convert/index.js' {
  declare module.exports: $Exports<'color-convert'>;
}
declare module 'color-convert/route.js' {
  declare module.exports: $Exports<'color-convert/route'>;
}
