// flow-typed signature: 72ea8bdb067050edf3ce4359739349ad
// flow-typed version: <<STUB>>/express-sanitized_v^0.5.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-sanitized'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-sanitized' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-sanitized/lib/express-sanitized' {
  declare module.exports: any;
}

declare module 'express-sanitized/test/express-sanitized' {
  declare module.exports: any;
}

declare module 'express-sanitized/testRunner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-sanitized/index' {
  declare module.exports: $Exports<'express-sanitized'>;
}
declare module 'express-sanitized/index.js' {
  declare module.exports: $Exports<'express-sanitized'>;
}
declare module 'express-sanitized/lib/express-sanitized.js' {
  declare module.exports: $Exports<'express-sanitized/lib/express-sanitized'>;
}
declare module 'express-sanitized/test/express-sanitized.js' {
  declare module.exports: $Exports<'express-sanitized/test/express-sanitized'>;
}
declare module 'express-sanitized/testRunner.js' {
  declare module.exports: $Exports<'express-sanitized/testRunner'>;
}
