// flow-typed signature: e15cb34a0c9e0a1087cb24d59de96d08
// flow-typed version: <<STUB>>/express-session-mongo_v^0.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-session-mongo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-session-mongo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-session-mongo/examples/app' {
  declare module.exports: any;
}

declare module 'express-session-mongo/lib/express-session-mongo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-session-mongo/examples/app.js' {
  declare module.exports: $Exports<'express-session-mongo/examples/app'>;
}
declare module 'express-session-mongo/lib/express-session-mongo.js' {
  declare module.exports: $Exports<'express-session-mongo/lib/express-session-mongo'>;
}
