// flow-typed signature: 65ab179776803ca51c3df376b3c1193c
// flow-typed version: <<STUB>>/grommet-toolbox_v^0.2.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grommet-toolbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grommet-toolbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grommet-toolbox/lib/gulp-options-builder' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/lib/gulp-tasks-core' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/lib/gulp-tasks-dev' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/lib/gulp-tasks-dist' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/lib/gulp-tasks-intl' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/lib/gulp-tasks-linters' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/lib/gulp-tasks-pack' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/lib/gulp-tasks-sync' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/lib/gulp-tasks-test' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/lib/gulp-tasks' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/lib/index' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/lib/utils/unique' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/lib/webpack.dev.config' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/lib/webpack.dist.config' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/src/gulp-options-builder' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/src/gulp-tasks-core' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/src/gulp-tasks-dev' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/src/gulp-tasks-dist' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/src/gulp-tasks-linters' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/src/gulp-tasks-pack' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/src/gulp-tasks-sync' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/src/gulp-tasks-test' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/src/gulp-tasks' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/src/index' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/src/utils/unique' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/src/webpack.dev.config' {
  declare module.exports: any;
}

declare module 'grommet-toolbox/src/webpack.dist.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grommet-toolbox/lib/gulp-options-builder.js' {
  declare module.exports: $Exports<'grommet-toolbox/lib/gulp-options-builder'>;
}
declare module 'grommet-toolbox/lib/gulp-tasks-core.js' {
  declare module.exports: $Exports<'grommet-toolbox/lib/gulp-tasks-core'>;
}
declare module 'grommet-toolbox/lib/gulp-tasks-dev.js' {
  declare module.exports: $Exports<'grommet-toolbox/lib/gulp-tasks-dev'>;
}
declare module 'grommet-toolbox/lib/gulp-tasks-dist.js' {
  declare module.exports: $Exports<'grommet-toolbox/lib/gulp-tasks-dist'>;
}
declare module 'grommet-toolbox/lib/gulp-tasks-intl.js' {
  declare module.exports: $Exports<'grommet-toolbox/lib/gulp-tasks-intl'>;
}
declare module 'grommet-toolbox/lib/gulp-tasks-linters.js' {
  declare module.exports: $Exports<'grommet-toolbox/lib/gulp-tasks-linters'>;
}
declare module 'grommet-toolbox/lib/gulp-tasks-pack.js' {
  declare module.exports: $Exports<'grommet-toolbox/lib/gulp-tasks-pack'>;
}
declare module 'grommet-toolbox/lib/gulp-tasks-sync.js' {
  declare module.exports: $Exports<'grommet-toolbox/lib/gulp-tasks-sync'>;
}
declare module 'grommet-toolbox/lib/gulp-tasks-test.js' {
  declare module.exports: $Exports<'grommet-toolbox/lib/gulp-tasks-test'>;
}
declare module 'grommet-toolbox/lib/gulp-tasks.js' {
  declare module.exports: $Exports<'grommet-toolbox/lib/gulp-tasks'>;
}
declare module 'grommet-toolbox/lib/index.js' {
  declare module.exports: $Exports<'grommet-toolbox/lib/index'>;
}
declare module 'grommet-toolbox/lib/utils/unique.js' {
  declare module.exports: $Exports<'grommet-toolbox/lib/utils/unique'>;
}
declare module 'grommet-toolbox/lib/webpack.dev.config.js' {
  declare module.exports: $Exports<'grommet-toolbox/lib/webpack.dev.config'>;
}
declare module 'grommet-toolbox/lib/webpack.dist.config.js' {
  declare module.exports: $Exports<'grommet-toolbox/lib/webpack.dist.config'>;
}
declare module 'grommet-toolbox/src/gulp-options-builder.js' {
  declare module.exports: $Exports<'grommet-toolbox/src/gulp-options-builder'>;
}
declare module 'grommet-toolbox/src/gulp-tasks-core.js' {
  declare module.exports: $Exports<'grommet-toolbox/src/gulp-tasks-core'>;
}
declare module 'grommet-toolbox/src/gulp-tasks-dev.js' {
  declare module.exports: $Exports<'grommet-toolbox/src/gulp-tasks-dev'>;
}
declare module 'grommet-toolbox/src/gulp-tasks-dist.js' {
  declare module.exports: $Exports<'grommet-toolbox/src/gulp-tasks-dist'>;
}
declare module 'grommet-toolbox/src/gulp-tasks-linters.js' {
  declare module.exports: $Exports<'grommet-toolbox/src/gulp-tasks-linters'>;
}
declare module 'grommet-toolbox/src/gulp-tasks-pack.js' {
  declare module.exports: $Exports<'grommet-toolbox/src/gulp-tasks-pack'>;
}
declare module 'grommet-toolbox/src/gulp-tasks-sync.js' {
  declare module.exports: $Exports<'grommet-toolbox/src/gulp-tasks-sync'>;
}
declare module 'grommet-toolbox/src/gulp-tasks-test.js' {
  declare module.exports: $Exports<'grommet-toolbox/src/gulp-tasks-test'>;
}
declare module 'grommet-toolbox/src/gulp-tasks.js' {
  declare module.exports: $Exports<'grommet-toolbox/src/gulp-tasks'>;
}
declare module 'grommet-toolbox/src/index.js' {
  declare module.exports: $Exports<'grommet-toolbox/src/index'>;
}
declare module 'grommet-toolbox/src/utils/unique.js' {
  declare module.exports: $Exports<'grommet-toolbox/src/utils/unique'>;
}
declare module 'grommet-toolbox/src/webpack.dev.config.js' {
  declare module.exports: $Exports<'grommet-toolbox/src/webpack.dev.config'>;
}
declare module 'grommet-toolbox/src/webpack.dist.config.js' {
  declare module.exports: $Exports<'grommet-toolbox/src/webpack.dist.config'>;
}
