// flow-typed signature: 18a66da9b8b8f2604dc032672cbf3fb6
// flow-typed version: <<STUB>>/grommet-addons^x.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grommet-addons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grommet-addons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grommet-addons/components/AnnotatedMeter' {
  declare module.exports: any;
}

declare module 'grommet-addons/components/FilterControl' {
  declare module.exports: any;
}

declare module 'grommet-addons/components/ListPlaceholder' {
  declare module.exports: any;
}

declare module 'grommet-addons/components/SideSplit' {
  declare module.exports: any;
}

declare module 'grommet-addons/components/Sort' {
  declare module.exports: any;
}
