// flow-typed signature: 3fe7bbe5c4b66d7ce68f79399fa06c6f
// flow-typed version: <<STUB>>/gulp-nodemon_v^2.0.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-nodemon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-nodemon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-nodemon/Gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-nodemon/test/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-nodemon/Gulpfile.js' {
  declare module.exports: $Exports<'gulp-nodemon/Gulpfile'>;
}
declare module 'gulp-nodemon/index' {
  declare module.exports: $Exports<'gulp-nodemon'>;
}
declare module 'gulp-nodemon/index.js' {
  declare module.exports: $Exports<'gulp-nodemon'>;
}
declare module 'gulp-nodemon/test/server.js' {
  declare module.exports: $Exports<'gulp-nodemon/test/server'>;
}
