// flow-typed signature: 65be8baccfc9cc94455952fb24532b66
// flow-typed version: <<STUB>>/gulp-git_v^1.2.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-git'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-git' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-git/examples/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-git/examples/test' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/add' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/addRemote' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/addSubmodule' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/branch' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/checkout' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/checkoutFiles' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/clean' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/clone' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/commit' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/exec' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/fetch' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/init' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/merge' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/pull' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/push' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/removeRemote' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/reset' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/revParse' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/rm' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/stash' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/status' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/tag' {
  declare module.exports: any;
}

declare module 'gulp-git/lib/updateSubmodule' {
  declare module.exports: any;
}

declare module 'gulp-git/test/_util' {
  declare module.exports: any;
}

declare module 'gulp-git/test/add' {
  declare module.exports: any;
}

declare module 'gulp-git/test/addRemote' {
  declare module.exports: any;
}

declare module 'gulp-git/test/branch' {
  declare module.exports: any;
}

declare module 'gulp-git/test/checkout' {
  declare module.exports: any;
}

declare module 'gulp-git/test/clean' {
  declare module.exports: any;
}

declare module 'gulp-git/test/clone' {
  declare module.exports: any;
}

declare module 'gulp-git/test/commit' {
  declare module.exports: any;
}

declare module 'gulp-git/test/exec' {
  declare module.exports: any;
}

declare module 'gulp-git/test/fetch' {
  declare module.exports: any;
}

declare module 'gulp-git/test/init' {
  declare module.exports: any;
}

declare module 'gulp-git/test/main' {
  declare module.exports: any;
}

declare module 'gulp-git/test/merge' {
  declare module.exports: any;
}

declare module 'gulp-git/test/pull' {
  declare module.exports: any;
}

declare module 'gulp-git/test/removeRemote' {
  declare module.exports: any;
}

declare module 'gulp-git/test/rm' {
  declare module.exports: any;
}

declare module 'gulp-git/test/stash' {
  declare module.exports: any;
}

declare module 'gulp-git/test/status' {
  declare module.exports: any;
}

declare module 'gulp-git/test/submodule' {
  declare module.exports: any;
}

declare module 'gulp-git/test/tag' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-git/examples/gulpfile.js' {
  declare module.exports: $Exports<'gulp-git/examples/gulpfile'>;
}
declare module 'gulp-git/examples/test.js' {
  declare module.exports: $Exports<'gulp-git/examples/test'>;
}
declare module 'gulp-git/index' {
  declare module.exports: $Exports<'gulp-git'>;
}
declare module 'gulp-git/index.js' {
  declare module.exports: $Exports<'gulp-git'>;
}
declare module 'gulp-git/lib/add.js' {
  declare module.exports: $Exports<'gulp-git/lib/add'>;
}
declare module 'gulp-git/lib/addRemote.js' {
  declare module.exports: $Exports<'gulp-git/lib/addRemote'>;
}
declare module 'gulp-git/lib/addSubmodule.js' {
  declare module.exports: $Exports<'gulp-git/lib/addSubmodule'>;
}
declare module 'gulp-git/lib/branch.js' {
  declare module.exports: $Exports<'gulp-git/lib/branch'>;
}
declare module 'gulp-git/lib/checkout.js' {
  declare module.exports: $Exports<'gulp-git/lib/checkout'>;
}
declare module 'gulp-git/lib/checkoutFiles.js' {
  declare module.exports: $Exports<'gulp-git/lib/checkoutFiles'>;
}
declare module 'gulp-git/lib/clean.js' {
  declare module.exports: $Exports<'gulp-git/lib/clean'>;
}
declare module 'gulp-git/lib/clone.js' {
  declare module.exports: $Exports<'gulp-git/lib/clone'>;
}
declare module 'gulp-git/lib/commit.js' {
  declare module.exports: $Exports<'gulp-git/lib/commit'>;
}
declare module 'gulp-git/lib/exec.js' {
  declare module.exports: $Exports<'gulp-git/lib/exec'>;
}
declare module 'gulp-git/lib/fetch.js' {
  declare module.exports: $Exports<'gulp-git/lib/fetch'>;
}
declare module 'gulp-git/lib/init.js' {
  declare module.exports: $Exports<'gulp-git/lib/init'>;
}
declare module 'gulp-git/lib/merge.js' {
  declare module.exports: $Exports<'gulp-git/lib/merge'>;
}
declare module 'gulp-git/lib/pull.js' {
  declare module.exports: $Exports<'gulp-git/lib/pull'>;
}
declare module 'gulp-git/lib/push.js' {
  declare module.exports: $Exports<'gulp-git/lib/push'>;
}
declare module 'gulp-git/lib/removeRemote.js' {
  declare module.exports: $Exports<'gulp-git/lib/removeRemote'>;
}
declare module 'gulp-git/lib/reset.js' {
  declare module.exports: $Exports<'gulp-git/lib/reset'>;
}
declare module 'gulp-git/lib/revParse.js' {
  declare module.exports: $Exports<'gulp-git/lib/revParse'>;
}
declare module 'gulp-git/lib/rm.js' {
  declare module.exports: $Exports<'gulp-git/lib/rm'>;
}
declare module 'gulp-git/lib/stash.js' {
  declare module.exports: $Exports<'gulp-git/lib/stash'>;
}
declare module 'gulp-git/lib/status.js' {
  declare module.exports: $Exports<'gulp-git/lib/status'>;
}
declare module 'gulp-git/lib/tag.js' {
  declare module.exports: $Exports<'gulp-git/lib/tag'>;
}
declare module 'gulp-git/lib/updateSubmodule.js' {
  declare module.exports: $Exports<'gulp-git/lib/updateSubmodule'>;
}
declare module 'gulp-git/test/_util.js' {
  declare module.exports: $Exports<'gulp-git/test/_util'>;
}
declare module 'gulp-git/test/add.js' {
  declare module.exports: $Exports<'gulp-git/test/add'>;
}
declare module 'gulp-git/test/addRemote.js' {
  declare module.exports: $Exports<'gulp-git/test/addRemote'>;
}
declare module 'gulp-git/test/branch.js' {
  declare module.exports: $Exports<'gulp-git/test/branch'>;
}
declare module 'gulp-git/test/checkout.js' {
  declare module.exports: $Exports<'gulp-git/test/checkout'>;
}
declare module 'gulp-git/test/clean.js' {
  declare module.exports: $Exports<'gulp-git/test/clean'>;
}
declare module 'gulp-git/test/clone.js' {
  declare module.exports: $Exports<'gulp-git/test/clone'>;
}
declare module 'gulp-git/test/commit.js' {
  declare module.exports: $Exports<'gulp-git/test/commit'>;
}
declare module 'gulp-git/test/exec.js' {
  declare module.exports: $Exports<'gulp-git/test/exec'>;
}
declare module 'gulp-git/test/fetch.js' {
  declare module.exports: $Exports<'gulp-git/test/fetch'>;
}
declare module 'gulp-git/test/init.js' {
  declare module.exports: $Exports<'gulp-git/test/init'>;
}
declare module 'gulp-git/test/main.js' {
  declare module.exports: $Exports<'gulp-git/test/main'>;
}
declare module 'gulp-git/test/merge.js' {
  declare module.exports: $Exports<'gulp-git/test/merge'>;
}
declare module 'gulp-git/test/pull.js' {
  declare module.exports: $Exports<'gulp-git/test/pull'>;
}
declare module 'gulp-git/test/removeRemote.js' {
  declare module.exports: $Exports<'gulp-git/test/removeRemote'>;
}
declare module 'gulp-git/test/rm.js' {
  declare module.exports: $Exports<'gulp-git/test/rm'>;
}
declare module 'gulp-git/test/stash.js' {
  declare module.exports: $Exports<'gulp-git/test/stash'>;
}
declare module 'gulp-git/test/status.js' {
  declare module.exports: $Exports<'gulp-git/test/status'>;
}
declare module 'gulp-git/test/submodule.js' {
  declare module.exports: $Exports<'gulp-git/test/submodule'>;
}
declare module 'gulp-git/test/tag.js' {
  declare module.exports: $Exports<'gulp-git/test/tag'>;
}
