// flow-typed signature: 9b191fccc5edd4fb84e18d65c521afaf
// flow-typed version: <<STUB>>/html-jsx-loader_v^0.1.12/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-jsx-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-jsx-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'html-jsx-loader/index' {
  declare module.exports: $Exports<'html-jsx-loader'>;
}
declare module 'html-jsx-loader/index.js' {
  declare module.exports: $Exports<'html-jsx-loader'>;
}
