// flow-typed signature: af991d8eff846592673129fd0a6fbe5d
// flow-typed version: <<STUB>>/mongoose-sequence_v^3.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose-sequence'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose-sequence' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongoose-sequence/Gruntfile' {
  declare module.exports: any;
}

declare module 'mongoose-sequence/lib/sequence_archive' {
  declare module.exports: any;
}

declare module 'mongoose-sequence/lib/sequence' {
  declare module.exports: any;
}

declare module 'mongoose-sequence/test/base' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongoose-sequence/Gruntfile.js' {
  declare module.exports: $Exports<'mongoose-sequence/Gruntfile'>;
}
declare module 'mongoose-sequence/index' {
  declare module.exports: $Exports<'mongoose-sequence'>;
}
declare module 'mongoose-sequence/index.js' {
  declare module.exports: $Exports<'mongoose-sequence'>;
}
declare module 'mongoose-sequence/lib/sequence_archive.js' {
  declare module.exports: $Exports<'mongoose-sequence/lib/sequence_archive'>;
}
declare module 'mongoose-sequence/lib/sequence.js' {
  declare module.exports: $Exports<'mongoose-sequence/lib/sequence'>;
}
declare module 'mongoose-sequence/test/base.js' {
  declare module.exports: $Exports<'mongoose-sequence/test/base'>;
}
