// flow-typed signature: a8b15cb1de1ecde41fd418bab30854db
// flow-typed version: <<STUB>>/mongoose-schema-extend_v^0.2.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose-schema-extend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose-schema-extend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongoose-schema-extend/Gruntfile' {
  declare module.exports: any;
}

declare module 'mongoose-schema-extend/test/discriminator' {
  declare module.exports: any;
}

declare module 'mongoose-schema-extend/test/extend' {
  declare module.exports: any;
}

declare module 'mongoose-schema-extend/test/fixtures/index' {
  declare module.exports: any;
}

declare module 'mongoose-schema-extend/test/indexes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongoose-schema-extend/Gruntfile.js' {
  declare module.exports: $Exports<'mongoose-schema-extend/Gruntfile'>;
}
declare module 'mongoose-schema-extend/index' {
  declare module.exports: $Exports<'mongoose-schema-extend'>;
}
declare module 'mongoose-schema-extend/index.js' {
  declare module.exports: $Exports<'mongoose-schema-extend'>;
}
declare module 'mongoose-schema-extend/test/discriminator.js' {
  declare module.exports: $Exports<'mongoose-schema-extend/test/discriminator'>;
}
declare module 'mongoose-schema-extend/test/extend.js' {
  declare module.exports: $Exports<'mongoose-schema-extend/test/extend'>;
}
declare module 'mongoose-schema-extend/test/fixtures/index.js' {
  declare module.exports: $Exports<'mongoose-schema-extend/test/fixtures/index'>;
}
declare module 'mongoose-schema-extend/test/indexes.js' {
  declare module.exports: $Exports<'mongoose-schema-extend/test/indexes'>;
}
