// flow-typed signature: ecc043ce458ce7aee0f8a463279e38d4
// flow-typed version: <<STUB>>/oauth_v^0.9.14/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'oauth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'oauth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'oauth/examples/express-gdata/server' {
  declare module.exports: any;
}

declare module 'oauth/examples/github-example' {
  declare module.exports: any;
}

declare module 'oauth/examples/term.ie.oauth-HMAC-SHA1' {
  declare module.exports: any;
}

declare module 'oauth/examples/twitter-example' {
  declare module.exports: any;
}

declare module 'oauth/lib/_utils' {
  declare module.exports: any;
}

declare module 'oauth/lib/oauth' {
  declare module.exports: any;
}

declare module 'oauth/lib/oauth2' {
  declare module.exports: any;
}

declare module 'oauth/lib/sha1' {
  declare module.exports: any;
}

declare module 'oauth/tests/oauth2tests' {
  declare module.exports: any;
}

declare module 'oauth/tests/oauthtests' {
  declare module.exports: any;
}

declare module 'oauth/tests/sha1tests' {
  declare module.exports: any;
}

declare module 'oauth/tests/shared' {
  declare module.exports: any;
}

// Filename aliases
declare module 'oauth/examples/express-gdata/server.js' {
  declare module.exports: $Exports<'oauth/examples/express-gdata/server'>;
}
declare module 'oauth/examples/github-example.js' {
  declare module.exports: $Exports<'oauth/examples/github-example'>;
}
declare module 'oauth/examples/term.ie.oauth-HMAC-SHA1.js' {
  declare module.exports: $Exports<'oauth/examples/term.ie.oauth-HMAC-SHA1'>;
}
declare module 'oauth/examples/twitter-example.js' {
  declare module.exports: $Exports<'oauth/examples/twitter-example'>;
}
declare module 'oauth/index' {
  declare module.exports: $Exports<'oauth'>;
}
declare module 'oauth/index.js' {
  declare module.exports: $Exports<'oauth'>;
}
declare module 'oauth/lib/_utils.js' {
  declare module.exports: $Exports<'oauth/lib/_utils'>;
}
declare module 'oauth/lib/oauth.js' {
  declare module.exports: $Exports<'oauth/lib/oauth'>;
}
declare module 'oauth/lib/oauth2.js' {
  declare module.exports: $Exports<'oauth/lib/oauth2'>;
}
declare module 'oauth/lib/sha1.js' {
  declare module.exports: $Exports<'oauth/lib/sha1'>;
}
declare module 'oauth/tests/oauth2tests.js' {
  declare module.exports: $Exports<'oauth/tests/oauth2tests'>;
}
declare module 'oauth/tests/oauthtests.js' {
  declare module.exports: $Exports<'oauth/tests/oauthtests'>;
}
declare module 'oauth/tests/sha1tests.js' {
  declare module.exports: $Exports<'oauth/tests/sha1tests'>;
}
declare module 'oauth/tests/shared.js' {
  declare module.exports: $Exports<'oauth/tests/shared'>;
}
