// flow-typed signature: 47e413ef379d8d0fcdcb67a21636d91c
// flow-typed version: <<STUB>>/plop_v^1.7.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'plop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'plop/example/plopfile' {
  declare module.exports: any;
}

declare module 'plop/src/console-out' {
  declare module.exports: any;
}

declare module 'plop/src/plop' {
  declare module.exports: any;
}

// Filename aliases
declare module 'plop/example/plopfile.js' {
  declare module.exports: $Exports<'plop/example/plopfile'>;
}
declare module 'plop/src/console-out.js' {
  declare module.exports: $Exports<'plop/src/console-out'>;
}
declare module 'plop/src/plop.js' {
  declare module.exports: $Exports<'plop/src/plop'>;
}
