// flow-typed signature: 4edfca3acb1a88c061a05b52cc258e61
// flow-typed version: <<STUB>>/react-scroll_v^1.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scroll/lib/__tests__/animate-scroll-test' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/__tests__/element-test' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/__tests__/events-test' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/__tests__/link-test' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/__tests__/page-test' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/components/Button' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/components/DirectLink' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/components/Element' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/components/Link' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/index' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/mixins/animate-scroll' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/mixins/cancel-events' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/mixins/direct-scroller' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/mixins/Helpers' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/mixins/passive-event-listeners' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/mixins/scroll-events' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/mixins/scroll-spy' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/mixins/scroller' {
  declare module.exports: any;
}

declare module 'react-scroll/lib/mixins/smooth' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scroll/lib/__tests__/animate-scroll-test.js' {
  declare module.exports: $Exports<'react-scroll/lib/__tests__/animate-scroll-test'>;
}
declare module 'react-scroll/lib/__tests__/element-test.js' {
  declare module.exports: $Exports<'react-scroll/lib/__tests__/element-test'>;
}
declare module 'react-scroll/lib/__tests__/events-test.js' {
  declare module.exports: $Exports<'react-scroll/lib/__tests__/events-test'>;
}
declare module 'react-scroll/lib/__tests__/link-test.js' {
  declare module.exports: $Exports<'react-scroll/lib/__tests__/link-test'>;
}
declare module 'react-scroll/lib/__tests__/page-test.js' {
  declare module.exports: $Exports<'react-scroll/lib/__tests__/page-test'>;
}
declare module 'react-scroll/lib/components/Button.js' {
  declare module.exports: $Exports<'react-scroll/lib/components/Button'>;
}
declare module 'react-scroll/lib/components/DirectLink.js' {
  declare module.exports: $Exports<'react-scroll/lib/components/DirectLink'>;
}
declare module 'react-scroll/lib/components/Element.js' {
  declare module.exports: $Exports<'react-scroll/lib/components/Element'>;
}
declare module 'react-scroll/lib/components/Link.js' {
  declare module.exports: $Exports<'react-scroll/lib/components/Link'>;
}
declare module 'react-scroll/lib/index.js' {
  declare module.exports: $Exports<'react-scroll/lib/index'>;
}
declare module 'react-scroll/lib/mixins/animate-scroll.js' {
  declare module.exports: $Exports<'react-scroll/lib/mixins/animate-scroll'>;
}
declare module 'react-scroll/lib/mixins/cancel-events.js' {
  declare module.exports: $Exports<'react-scroll/lib/mixins/cancel-events'>;
}
declare module 'react-scroll/lib/mixins/direct-scroller.js' {
  declare module.exports: $Exports<'react-scroll/lib/mixins/direct-scroller'>;
}
declare module 'react-scroll/lib/mixins/Helpers.js' {
  declare module.exports: $Exports<'react-scroll/lib/mixins/Helpers'>;
}
declare module 'react-scroll/lib/mixins/passive-event-listeners.js' {
  declare module.exports: $Exports<'react-scroll/lib/mixins/passive-event-listeners'>;
}
declare module 'react-scroll/lib/mixins/scroll-events.js' {
  declare module.exports: $Exports<'react-scroll/lib/mixins/scroll-events'>;
}
declare module 'react-scroll/lib/mixins/scroll-spy.js' {
  declare module.exports: $Exports<'react-scroll/lib/mixins/scroll-spy'>;
}
declare module 'react-scroll/lib/mixins/scroller.js' {
  declare module.exports: $Exports<'react-scroll/lib/mixins/scroller'>;
}
declare module 'react-scroll/lib/mixins/smooth.js' {
  declare module.exports: $Exports<'react-scroll/lib/mixins/smooth'>;
}
