// flow-typed signature: 71b5d05d9b0b1073c514b17b09d7666d
// flow-typed version: <<STUB>>/redux-router_v^2.1.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-router/dist/redux-router' {
  declare module.exports: any;
}

declare module 'redux-router/dist/redux-router.min' {
  declare module.exports: any;
}

declare module 'redux-router/lib/__tests__/init' {
  declare module.exports: any;
}

declare module 'redux-router/lib/__tests__/reduxReactRouter-test' {
  declare module.exports: any;
}

declare module 'redux-router/lib/__tests__/ReduxRouter-test' {
  declare module.exports: any;
}

declare module 'redux-router/lib/actionCreators' {
  declare module.exports: any;
}

declare module 'redux-router/lib/client' {
  declare module.exports: any;
}

declare module 'redux-router/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-router/lib/historyMiddleware' {
  declare module.exports: any;
}

declare module 'redux-router/lib/index' {
  declare module.exports: any;
}

declare module 'redux-router/lib/isActive' {
  declare module.exports: any;
}

declare module 'redux-router/lib/matchMiddleware' {
  declare module.exports: any;
}

declare module 'redux-router/lib/reduxReactRouter' {
  declare module.exports: any;
}

declare module 'redux-router/lib/ReduxRouter' {
  declare module.exports: any;
}

declare module 'redux-router/lib/replaceRoutesMiddleware' {
  declare module.exports: any;
}

declare module 'redux-router/lib/routeReplacement' {
  declare module.exports: any;
}

declare module 'redux-router/lib/routerStateEquals' {
  declare module.exports: any;
}

declare module 'redux-router/lib/routerStateReducer' {
  declare module.exports: any;
}

declare module 'redux-router/lib/server' {
  declare module.exports: any;
}

declare module 'redux-router/lib/serverModule' {
  declare module.exports: any;
}

declare module 'redux-router/lib/useDefaults' {
  declare module.exports: any;
}

declare module 'redux-router/server' {
  declare module.exports: any;
}

declare module 'redux-router/src/__tests__/init' {
  declare module.exports: any;
}

declare module 'redux-router/src/__tests__/reduxReactRouter-test' {
  declare module.exports: any;
}

declare module 'redux-router/src/__tests__/ReduxRouter-test' {
  declare module.exports: any;
}

declare module 'redux-router/src/actionCreators' {
  declare module.exports: any;
}

declare module 'redux-router/src/client' {
  declare module.exports: any;
}

declare module 'redux-router/src/constants' {
  declare module.exports: any;
}

declare module 'redux-router/src/historyMiddleware' {
  declare module.exports: any;
}

declare module 'redux-router/src/index' {
  declare module.exports: any;
}

declare module 'redux-router/src/isActive' {
  declare module.exports: any;
}

declare module 'redux-router/src/matchMiddleware' {
  declare module.exports: any;
}

declare module 'redux-router/src/reduxReactRouter' {
  declare module.exports: any;
}

declare module 'redux-router/src/ReduxRouter' {
  declare module.exports: any;
}

declare module 'redux-router/src/replaceRoutesMiddleware' {
  declare module.exports: any;
}

declare module 'redux-router/src/routeReplacement' {
  declare module.exports: any;
}

declare module 'redux-router/src/routerStateEquals' {
  declare module.exports: any;
}

declare module 'redux-router/src/routerStateReducer' {
  declare module.exports: any;
}

declare module 'redux-router/src/server' {
  declare module.exports: any;
}

declare module 'redux-router/src/serverModule' {
  declare module.exports: any;
}

declare module 'redux-router/src/useDefaults' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-router/dist/redux-router.js' {
  declare module.exports: $Exports<'redux-router/dist/redux-router'>;
}
declare module 'redux-router/dist/redux-router.min.js' {
  declare module.exports: $Exports<'redux-router/dist/redux-router.min'>;
}
declare module 'redux-router/lib/__tests__/init.js' {
  declare module.exports: $Exports<'redux-router/lib/__tests__/init'>;
}
declare module 'redux-router/lib/__tests__/reduxReactRouter-test.js' {
  declare module.exports: $Exports<'redux-router/lib/__tests__/reduxReactRouter-test'>;
}
declare module 'redux-router/lib/__tests__/ReduxRouter-test.js' {
  declare module.exports: $Exports<'redux-router/lib/__tests__/ReduxRouter-test'>;
}
declare module 'redux-router/lib/actionCreators.js' {
  declare module.exports: $Exports<'redux-router/lib/actionCreators'>;
}
declare module 'redux-router/lib/client.js' {
  declare module.exports: $Exports<'redux-router/lib/client'>;
}
declare module 'redux-router/lib/constants.js' {
  declare module.exports: $Exports<'redux-router/lib/constants'>;
}
declare module 'redux-router/lib/historyMiddleware.js' {
  declare module.exports: $Exports<'redux-router/lib/historyMiddleware'>;
}
declare module 'redux-router/lib/index.js' {
  declare module.exports: $Exports<'redux-router/lib/index'>;
}
declare module 'redux-router/lib/isActive.js' {
  declare module.exports: $Exports<'redux-router/lib/isActive'>;
}
declare module 'redux-router/lib/matchMiddleware.js' {
  declare module.exports: $Exports<'redux-router/lib/matchMiddleware'>;
}
declare module 'redux-router/lib/reduxReactRouter.js' {
  declare module.exports: $Exports<'redux-router/lib/reduxReactRouter'>;
}
declare module 'redux-router/lib/ReduxRouter.js' {
  declare module.exports: $Exports<'redux-router/lib/ReduxRouter'>;
}
declare module 'redux-router/lib/replaceRoutesMiddleware.js' {
  declare module.exports: $Exports<'redux-router/lib/replaceRoutesMiddleware'>;
}
declare module 'redux-router/lib/routeReplacement.js' {
  declare module.exports: $Exports<'redux-router/lib/routeReplacement'>;
}
declare module 'redux-router/lib/routerStateEquals.js' {
  declare module.exports: $Exports<'redux-router/lib/routerStateEquals'>;
}
declare module 'redux-router/lib/routerStateReducer.js' {
  declare module.exports: $Exports<'redux-router/lib/routerStateReducer'>;
}
declare module 'redux-router/lib/server.js' {
  declare module.exports: $Exports<'redux-router/lib/server'>;
}
declare module 'redux-router/lib/serverModule.js' {
  declare module.exports: $Exports<'redux-router/lib/serverModule'>;
}
declare module 'redux-router/lib/useDefaults.js' {
  declare module.exports: $Exports<'redux-router/lib/useDefaults'>;
}
declare module 'redux-router/server.js' {
  declare module.exports: $Exports<'redux-router/server'>;
}
declare module 'redux-router/src/__tests__/init.js' {
  declare module.exports: $Exports<'redux-router/src/__tests__/init'>;
}
declare module 'redux-router/src/__tests__/reduxReactRouter-test.js' {
  declare module.exports: $Exports<'redux-router/src/__tests__/reduxReactRouter-test'>;
}
declare module 'redux-router/src/__tests__/ReduxRouter-test.js' {
  declare module.exports: $Exports<'redux-router/src/__tests__/ReduxRouter-test'>;
}
declare module 'redux-router/src/actionCreators.js' {
  declare module.exports: $Exports<'redux-router/src/actionCreators'>;
}
declare module 'redux-router/src/client.js' {
  declare module.exports: $Exports<'redux-router/src/client'>;
}
declare module 'redux-router/src/constants.js' {
  declare module.exports: $Exports<'redux-router/src/constants'>;
}
declare module 'redux-router/src/historyMiddleware.js' {
  declare module.exports: $Exports<'redux-router/src/historyMiddleware'>;
}
declare module 'redux-router/src/index.js' {
  declare module.exports: $Exports<'redux-router/src/index'>;
}
declare module 'redux-router/src/isActive.js' {
  declare module.exports: $Exports<'redux-router/src/isActive'>;
}
declare module 'redux-router/src/matchMiddleware.js' {
  declare module.exports: $Exports<'redux-router/src/matchMiddleware'>;
}
declare module 'redux-router/src/reduxReactRouter.js' {
  declare module.exports: $Exports<'redux-router/src/reduxReactRouter'>;
}
declare module 'redux-router/src/ReduxRouter.js' {
  declare module.exports: $Exports<'redux-router/src/ReduxRouter'>;
}
declare module 'redux-router/src/replaceRoutesMiddleware.js' {
  declare module.exports: $Exports<'redux-router/src/replaceRoutesMiddleware'>;
}
declare module 'redux-router/src/routeReplacement.js' {
  declare module.exports: $Exports<'redux-router/src/routeReplacement'>;
}
declare module 'redux-router/src/routerStateEquals.js' {
  declare module.exports: $Exports<'redux-router/src/routerStateEquals'>;
}
declare module 'redux-router/src/routerStateReducer.js' {
  declare module.exports: $Exports<'redux-router/src/routerStateReducer'>;
}
declare module 'redux-router/src/server.js' {
  declare module.exports: $Exports<'redux-router/src/server'>;
}
declare module 'redux-router/src/serverModule.js' {
  declare module.exports: $Exports<'redux-router/src/serverModule'>;
}
declare module 'redux-router/src/useDefaults.js' {
  declare module.exports: $Exports<'redux-router/src/useDefaults'>;
}
