// flow-typed signature: 4c059fb7ed5a708a43ce44662da35bde
// flow-typed version: <<STUB>>/remarkable_v^1.7.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remarkable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'remarkable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remarkable/benchmark/implementations/commonmark-reference/index' {
  declare module.exports: any;
}

declare module 'remarkable/benchmark/implementations/current-commonmark/index' {
  declare module.exports: any;
}

declare module 'remarkable/benchmark/implementations/current/index' {
  declare module.exports: any;
}

declare module 'remarkable/benchmark/implementations/marked-0.3.2/index' {
  declare module.exports: any;
}

declare module 'remarkable/benchmark/index' {
  declare module.exports: any;
}

declare module 'remarkable/benchmark/profile' {
  declare module.exports: any;
}

declare module 'remarkable/bin/remarkable' {
  declare module.exports: any;
}

declare module 'remarkable/demo/assets/index' {
  declare module.exports: any;
}

declare module 'remarkable/demo/example' {
  declare module.exports: any;
}

declare module 'remarkable/dist/remarkable' {
  declare module.exports: any;
}

declare module 'remarkable/dist/remarkable.min' {
  declare module.exports: any;
}

declare module 'remarkable/lib/common/entities' {
  declare module.exports: any;
}

declare module 'remarkable/lib/common/html_blocks' {
  declare module.exports: any;
}

declare module 'remarkable/lib/common/html_re' {
  declare module.exports: any;
}

declare module 'remarkable/lib/common/url_schemas' {
  declare module.exports: any;
}

declare module 'remarkable/lib/common/utils' {
  declare module.exports: any;
}

declare module 'remarkable/lib/configs/commonmark' {
  declare module.exports: any;
}

declare module 'remarkable/lib/configs/default' {
  declare module.exports: any;
}

declare module 'remarkable/lib/configs/full' {
  declare module.exports: any;
}

declare module 'remarkable/lib/helpers/normalize_link' {
  declare module.exports: any;
}

declare module 'remarkable/lib/helpers/normalize_reference' {
  declare module.exports: any;
}

declare module 'remarkable/lib/helpers/parse_link_destination' {
  declare module.exports: any;
}

declare module 'remarkable/lib/helpers/parse_link_label' {
  declare module.exports: any;
}

declare module 'remarkable/lib/helpers/parse_link_title' {
  declare module.exports: any;
}

declare module 'remarkable/lib/index' {
  declare module.exports: any;
}

declare module 'remarkable/lib/parser_block' {
  declare module.exports: any;
}

declare module 'remarkable/lib/parser_core' {
  declare module.exports: any;
}

declare module 'remarkable/lib/parser_inline' {
  declare module.exports: any;
}

declare module 'remarkable/lib/renderer' {
  declare module.exports: any;
}

declare module 'remarkable/lib/ruler' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_block/blockquote' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_block/code' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_block/deflist' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_block/fences' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_block/footnote' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_block/heading' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_block/hr' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_block/htmlblock' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_block/lheading' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_block/list' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_block/paragraph' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_block/state_block' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_block/table' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_core/abbr' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_core/abbr2' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_core/block' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_core/footnote_tail' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_core/inline' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_core/linkify' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_core/references' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_core/replacements' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_core/smartquotes' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/autolink' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/backticks' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/del' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/emphasis' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/entity' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/escape' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/footnote_inline' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/footnote_ref' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/htmltag' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/ins' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/links' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/mark' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/newline' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/state_inline' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/sub' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/sup' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules_inline/text' {
  declare module.exports: any;
}

declare module 'remarkable/lib/rules' {
  declare module.exports: any;
}

declare module 'remarkable/support/demodata' {
  declare module.exports: any;
}

declare module 'remarkable/support/entities' {
  declare module.exports: any;
}

declare module 'remarkable/support/specsplit' {
  declare module.exports: any;
}

declare module 'remarkable/test/commonmark' {
  declare module.exports: any;
}

declare module 'remarkable/test/misc' {
  declare module.exports: any;
}

declare module 'remarkable/test/remarkable' {
  declare module.exports: any;
}

declare module 'remarkable/test/ruler' {
  declare module.exports: any;
}

declare module 'remarkable/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remarkable/benchmark/implementations/commonmark-reference/index.js' {
  declare module.exports: $Exports<'remarkable/benchmark/implementations/commonmark-reference/index'>;
}
declare module 'remarkable/benchmark/implementations/current-commonmark/index.js' {
  declare module.exports: $Exports<'remarkable/benchmark/implementations/current-commonmark/index'>;
}
declare module 'remarkable/benchmark/implementations/current/index.js' {
  declare module.exports: $Exports<'remarkable/benchmark/implementations/current/index'>;
}
declare module 'remarkable/benchmark/implementations/marked-0.3.2/index.js' {
  declare module.exports: $Exports<'remarkable/benchmark/implementations/marked-0.3.2/index'>;
}
declare module 'remarkable/benchmark/index.js' {
  declare module.exports: $Exports<'remarkable/benchmark/index'>;
}
declare module 'remarkable/benchmark/profile.js' {
  declare module.exports: $Exports<'remarkable/benchmark/profile'>;
}
declare module 'remarkable/bin/remarkable.js' {
  declare module.exports: $Exports<'remarkable/bin/remarkable'>;
}
declare module 'remarkable/demo/assets/index.js' {
  declare module.exports: $Exports<'remarkable/demo/assets/index'>;
}
declare module 'remarkable/demo/example.js' {
  declare module.exports: $Exports<'remarkable/demo/example'>;
}
declare module 'remarkable/dist/remarkable.js' {
  declare module.exports: $Exports<'remarkable/dist/remarkable'>;
}
declare module 'remarkable/dist/remarkable.min.js' {
  declare module.exports: $Exports<'remarkable/dist/remarkable.min'>;
}
declare module 'remarkable/index' {
  declare module.exports: $Exports<'remarkable'>;
}
declare module 'remarkable/index.js' {
  declare module.exports: $Exports<'remarkable'>;
}
declare module 'remarkable/lib/common/entities.js' {
  declare module.exports: $Exports<'remarkable/lib/common/entities'>;
}
declare module 'remarkable/lib/common/html_blocks.js' {
  declare module.exports: $Exports<'remarkable/lib/common/html_blocks'>;
}
declare module 'remarkable/lib/common/html_re.js' {
  declare module.exports: $Exports<'remarkable/lib/common/html_re'>;
}
declare module 'remarkable/lib/common/url_schemas.js' {
  declare module.exports: $Exports<'remarkable/lib/common/url_schemas'>;
}
declare module 'remarkable/lib/common/utils.js' {
  declare module.exports: $Exports<'remarkable/lib/common/utils'>;
}
declare module 'remarkable/lib/configs/commonmark.js' {
  declare module.exports: $Exports<'remarkable/lib/configs/commonmark'>;
}
declare module 'remarkable/lib/configs/default.js' {
  declare module.exports: $Exports<'remarkable/lib/configs/default'>;
}
declare module 'remarkable/lib/configs/full.js' {
  declare module.exports: $Exports<'remarkable/lib/configs/full'>;
}
declare module 'remarkable/lib/helpers/normalize_link.js' {
  declare module.exports: $Exports<'remarkable/lib/helpers/normalize_link'>;
}
declare module 'remarkable/lib/helpers/normalize_reference.js' {
  declare module.exports: $Exports<'remarkable/lib/helpers/normalize_reference'>;
}
declare module 'remarkable/lib/helpers/parse_link_destination.js' {
  declare module.exports: $Exports<'remarkable/lib/helpers/parse_link_destination'>;
}
declare module 'remarkable/lib/helpers/parse_link_label.js' {
  declare module.exports: $Exports<'remarkable/lib/helpers/parse_link_label'>;
}
declare module 'remarkable/lib/helpers/parse_link_title.js' {
  declare module.exports: $Exports<'remarkable/lib/helpers/parse_link_title'>;
}
declare module 'remarkable/lib/index.js' {
  declare module.exports: $Exports<'remarkable/lib/index'>;
}
declare module 'remarkable/lib/parser_block.js' {
  declare module.exports: $Exports<'remarkable/lib/parser_block'>;
}
declare module 'remarkable/lib/parser_core.js' {
  declare module.exports: $Exports<'remarkable/lib/parser_core'>;
}
declare module 'remarkable/lib/parser_inline.js' {
  declare module.exports: $Exports<'remarkable/lib/parser_inline'>;
}
declare module 'remarkable/lib/renderer.js' {
  declare module.exports: $Exports<'remarkable/lib/renderer'>;
}
declare module 'remarkable/lib/ruler.js' {
  declare module.exports: $Exports<'remarkable/lib/ruler'>;
}
declare module 'remarkable/lib/rules_block/blockquote.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_block/blockquote'>;
}
declare module 'remarkable/lib/rules_block/code.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_block/code'>;
}
declare module 'remarkable/lib/rules_block/deflist.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_block/deflist'>;
}
declare module 'remarkable/lib/rules_block/fences.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_block/fences'>;
}
declare module 'remarkable/lib/rules_block/footnote.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_block/footnote'>;
}
declare module 'remarkable/lib/rules_block/heading.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_block/heading'>;
}
declare module 'remarkable/lib/rules_block/hr.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_block/hr'>;
}
declare module 'remarkable/lib/rules_block/htmlblock.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_block/htmlblock'>;
}
declare module 'remarkable/lib/rules_block/lheading.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_block/lheading'>;
}
declare module 'remarkable/lib/rules_block/list.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_block/list'>;
}
declare module 'remarkable/lib/rules_block/paragraph.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_block/paragraph'>;
}
declare module 'remarkable/lib/rules_block/state_block.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_block/state_block'>;
}
declare module 'remarkable/lib/rules_block/table.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_block/table'>;
}
declare module 'remarkable/lib/rules_core/abbr.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_core/abbr'>;
}
declare module 'remarkable/lib/rules_core/abbr2.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_core/abbr2'>;
}
declare module 'remarkable/lib/rules_core/block.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_core/block'>;
}
declare module 'remarkable/lib/rules_core/footnote_tail.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_core/footnote_tail'>;
}
declare module 'remarkable/lib/rules_core/inline.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_core/inline'>;
}
declare module 'remarkable/lib/rules_core/linkify.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_core/linkify'>;
}
declare module 'remarkable/lib/rules_core/references.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_core/references'>;
}
declare module 'remarkable/lib/rules_core/replacements.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_core/replacements'>;
}
declare module 'remarkable/lib/rules_core/smartquotes.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_core/smartquotes'>;
}
declare module 'remarkable/lib/rules_inline/autolink.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/autolink'>;
}
declare module 'remarkable/lib/rules_inline/backticks.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/backticks'>;
}
declare module 'remarkable/lib/rules_inline/del.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/del'>;
}
declare module 'remarkable/lib/rules_inline/emphasis.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/emphasis'>;
}
declare module 'remarkable/lib/rules_inline/entity.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/entity'>;
}
declare module 'remarkable/lib/rules_inline/escape.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/escape'>;
}
declare module 'remarkable/lib/rules_inline/footnote_inline.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/footnote_inline'>;
}
declare module 'remarkable/lib/rules_inline/footnote_ref.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/footnote_ref'>;
}
declare module 'remarkable/lib/rules_inline/htmltag.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/htmltag'>;
}
declare module 'remarkable/lib/rules_inline/ins.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/ins'>;
}
declare module 'remarkable/lib/rules_inline/links.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/links'>;
}
declare module 'remarkable/lib/rules_inline/mark.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/mark'>;
}
declare module 'remarkable/lib/rules_inline/newline.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/newline'>;
}
declare module 'remarkable/lib/rules_inline/state_inline.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/state_inline'>;
}
declare module 'remarkable/lib/rules_inline/sub.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/sub'>;
}
declare module 'remarkable/lib/rules_inline/sup.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/sup'>;
}
declare module 'remarkable/lib/rules_inline/text.js' {
  declare module.exports: $Exports<'remarkable/lib/rules_inline/text'>;
}
declare module 'remarkable/lib/rules.js' {
  declare module.exports: $Exports<'remarkable/lib/rules'>;
}
declare module 'remarkable/support/demodata.js' {
  declare module.exports: $Exports<'remarkable/support/demodata'>;
}
declare module 'remarkable/support/entities.js' {
  declare module.exports: $Exports<'remarkable/support/entities'>;
}
declare module 'remarkable/support/specsplit.js' {
  declare module.exports: $Exports<'remarkable/support/specsplit'>;
}
declare module 'remarkable/test/commonmark.js' {
  declare module.exports: $Exports<'remarkable/test/commonmark'>;
}
declare module 'remarkable/test/misc.js' {
  declare module.exports: $Exports<'remarkable/test/misc'>;
}
declare module 'remarkable/test/remarkable.js' {
  declare module.exports: $Exports<'remarkable/test/remarkable'>;
}
declare module 'remarkable/test/ruler.js' {
  declare module.exports: $Exports<'remarkable/test/ruler'>;
}
declare module 'remarkable/test/utils.js' {
  declare module.exports: $Exports<'remarkable/test/utils'>;
}
