// flow-typed signature: 54d94fe8e56636527d2181544487f3ff
// flow-typed version: <<STUB>>/styled-components_vlatest/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components' {
  declare module.exports: any;
}
