// flow-typed signature: d79eb2cd590b67f5d8c4f6bcfe28c5d3
// flow-typed version: <<STUB>>/token-generator_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'token-generator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'token-generator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'token-generator/index' {
  declare module.exports: $Exports<'token-generator'>;
}
declare module 'token-generator/index.js' {
  declare module.exports: $Exports<'token-generator'>;
}
