// flow-typed signature: 06f14c035ac2e4452c77690e8a23109d
// flow-typed version: <<STUB>>/walk_v^2.3.9/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'walk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'walk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'walk/lib/node-type-emitter' {
  declare module.exports: any;
}

declare module 'walk/lib/walk-async-only' {
  declare module.exports: any;
}

declare module 'walk/lib/walk' {
  declare module.exports: any;
}

// Filename aliases
declare module 'walk/lib/node-type-emitter.js' {
  declare module.exports: $Exports<'walk/lib/node-type-emitter'>;
}
declare module 'walk/lib/walk-async-only.js' {
  declare module.exports: $Exports<'walk/lib/walk-async-only'>;
}
declare module 'walk/lib/walk.js' {
  declare module.exports: $Exports<'walk/lib/walk'>;
}
