// flow-typed signature: 827ac0c1cd431ae1521a15262d002b55
// flow-typed version: <<STUB>>/webpack-stream_v^3.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-stream/index' {
  declare module.exports: $Exports<'webpack-stream'>;
}
declare module 'webpack-stream/index.js' {
  declare module.exports: $Exports<'webpack-stream'>;
}
