export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';
export const DASHBOARD_ERROR = 'DASHBOARD_ERROR';
export const DASHBOARD_SET_LEFT_NAV_ANCHOR = 'DASHBOARD_SET_LEFT_NAV_ANCHOR';
export const DASHBOARD_LOAD_NAV_SUCCESS = 'DASHBOARD_LOAD_NAV_SUCCESS';
