export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_CREATE_ERROR = 'USER_CREATE_ERROR';
