export const FILE_INSERT_REQUEST = 'FILE_INSERT_REQUEST';
export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST';
export const FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
