export const LOAD_DATA_INITIATION = 'SETTINGS/LOAD_DATA_INITIATION';
export const LOAD_DATA_FAILURE = 'SETTINGS/LOAD_DATA_FAILURE';
export const LOAD_DATA_SUCCESS = 'SETTINGS/LOAD_DATA_SUCCESS';

export const FORM_INPUT = 'SETTINGS/FORM_INPUT';

export const SUBMIT_DATA_INITIATION = 'SETTINGS/SUBMIT_DATA_INITIATION';
export const SUBMIT_DATA_SUCCESS = 'SETTINGS/SUBMIT_DATA_SUCCESS';
export const SUBMIT_DATA_FAILURE = 'SETTINGS/SUBMIT_DATA_FAILURE';

export const CLEAR_ERROR = 'SETTINGS/CLEAR_ERROR';
export const CLEAR_MESSAGE = 'SETTINGS/CLEAR_MESSAGE';
export const REMOVE_LOGO = 'SETTINGS/REMOVE_LOGO';
