import type {
  TOGGLE_FORM_TYPE, SET_FORM_OPTIONS_TYPE,
  SET_SEARCH_TERM_TYPE, SET_FORM_FUNCTIONS_TYPE,
  SET_FORM_FIELD_VALUE_TYPE, CLEAR_FORM_TYPE,
  TOGGLE_FILTER_RESET_TYPE, TOGGLE_LIST_TYPE_TYPE,
  TOGGLE_TABLE_SORT_ORDER_TYPE, SET_SORT_INDEX_TYPE,
  SET_CHECK_BOX_TYPE, OPEN_CONFIRM_LAYER_TYPE,
  CLOSE_CONFIRM_LAYER_TYPE, CLEAR_SELECTED_INDICIES_TYPE
} from './flowTypes';

export const TOGGLE_FORM: TOGGLE_FORM_TYPE = 'DASH_ASSETS_LIST/TOGGLE_FORM';
export const SET_FORM_OPTIONS: SET_FORM_OPTIONS_TYPE = 'DASH_ASSETS_LIST/SET_FORM_OPTIONS';
export const SET_SEARCH_TERM: SET_SEARCH_TERM_TYPE = 'DASH_ASSETS_LIST/SET_SEARCH_TERM';
export const SET_FORM_FUNCTIONS: SET_FORM_FUNCTIONS_TYPE = 'DASH_ASSETS_LIST/SET_FORM_FUNCTIONS';
export const SET_FORM_FIELD_VALUE: SET_FORM_FIELD_VALUE_TYPE = 'DASH_ASSETS_LIST/SET_FORM_FIELD_VALUE';
export const CLEAR_FORM: CLEAR_FORM_TYPE = 'DASH_ASSETS_LIST/CLEAR_FORM';
export const TOGGLE_FILTER_RESET: TOGGLE_FILTER_RESET_TYPE = 'DASH_ASSETS_LIST/TOGGLE_FILTER_RESET';
export const TOGGLE_LIST_TYPE: TOGGLE_LIST_TYPE_TYPE = 'DASH_ASSETS_LIST/TOGGLE_LIST_TYPE';
export const TOGGLE_TABLE_SORT_ORDER: TOGGLE_TABLE_SORT_ORDER_TYPE = 'DASH_ASSETS_LIST/TOGGLE_TABLE_SORT_ORDER';
export const SET_SORT_INDEX: SET_SORT_INDEX_TYPE = 'DASH_ASSETS_LIST/SET_SORT_INDEX';
export const SET_CHECK_BOX: SET_CHECK_BOX_TYPE = 'DASH_ASSETS_LIST/SET_CHECK_BOX';
export const OPEN_CONFIRM_LAYER: OPEN_CONFIRM_LAYER_TYPE = 'DASH_ASSETS_LIST/OPEN_CONFIRM_LAYER';
export const CLOSE_CONFIRM_LAYER: CLOSE_CONFIRM_LAYER_TYPE = 'DASH_ASSETS_LIST/CLOSE_CONFIRM_LAYER';
export const CLEAR_SELECTED_INDICIES: CLEAR_SELECTED_INDICIES_TYPE = 'DASH_ASSETS_LIST/CLEAR_SELECTED_INDICIES';
