export const DASHBOARD_POSTS_TOGGLE_FORM = 'DASHBOARD_POSTS_TOGGLE_FORM';
export const DASHBOARD_POSTS_ADD_POST_REDIRECT = 'DASHBOARD_POSTS_ADD_POST_REDIRECT';
export const DASHBOARD_POSTS_INCREMENT_CURRENT_PAGE = 'DASHBOARD_POSTS_INCREMENT_CURRENT_PAGE';
