export const LOAD_DATA_INITIATION = 'DASHBOARD_SETTINGS/LOAD_DATA_INITIATION';
export const LOAD_DATA_FAILURE = 'DASHBOARD_SETTINGS/LOAD_DATA_FAILURE';
export const LOAD_DATA_SUCCESS = 'DASHBOARD_SETTINGS/LOAD_DATA_SUCCESS';
