/* @flow */
import type {
  SHOW_SECTION_FORM_TYPE,
  POST_SECTION_FORM_INPUT_TYPE,
  POST_SECTION_FORM_RESET_TYPE,
  POST_SECTION_SET_MESSAGE_TYPE,
  POST_SECTION_CLEAR_MESSAGE_TYPE,
  POST_TOGGLE_BOX_LAYOUT_FORM_TYPE,
  POST_BOX_LAYOUT_FORM_INPUT_TYPE,
  SHOW_BOX_LAYOUT_FORM_TYPE,
  POST_BOX_LAYOUT_FORM_RESET_TYPE,
  POST_TOGGLE_ADVANCED_LAYOUT_TYPE,
  POST_TOGGLE_HELP_TYPE,
  CONFIRM_DELETION_TYPE,
  CANCEL_DELETION_TYPE
} from './flowTypes';
export const SHOW_SECTION_FORM: SHOW_SECTION_FORM_TYPE =
  'DASHBOARD_POST_PAGE/SHOW_SECTION_FORM';
export const POST_SECTION_FORM_INPUT: POST_SECTION_FORM_INPUT_TYPE =
  'DASHBOARD_POST_PAGE/POST_SECTION_FORM_INPUT';
export const POST_SECTION_FORM_RESET: POST_SECTION_FORM_RESET_TYPE =
  'DASHBOARD_POST_PAGE/POST_SECTION_FORM_RESET';
export const POST_SECTION_SET_MESSAGE: POST_SECTION_SET_MESSAGE_TYPE =
  'DASHBOARD_POST_PAGE/POST_SECTION_SET_MESSAGE';
export const POST_SECTION_CLEAR_MESSAGE: POST_SECTION_CLEAR_MESSAGE_TYPE =
  'DASHBOARD_POST_PAGE/POST_SECTION_CLEAR_MESSAGE';
export const POST_TOGGLE_BOX_LAYOUT_FORM: POST_TOGGLE_BOX_LAYOUT_FORM_TYPE =
  'DASHBOARD_POST_PAGE/POST_TOGGLE_BOX_LAYOUT_FORM';
export const POST_BOX_LAYOUT_FORM_INPUT: POST_BOX_LAYOUT_FORM_INPUT_TYPE =
  'DASHBOARD_POST_PAGE/POST_BOX_LAYOUT_FORM_INPUT';
export const SHOW_BOX_LAYOUT_FORM: SHOW_BOX_LAYOUT_FORM_TYPE =
  'DASHBOARD_POST_PAGE/SHOW_BOX_LAYOUT_FORM';
export const POST_BOX_LAYOUT_FORM_RESET: POST_BOX_LAYOUT_FORM_RESET_TYPE =
  'DASHBOARD_POST_PAGE/POST_BOX_LAYOUT_FORM_RESET';
export const POST_TOGGLE_ADVANCED_LAYOUT: POST_TOGGLE_ADVANCED_LAYOUT_TYPE =
  'DASHBOARD_POST_PAGE/POST_TOGGLE_ADVANCED_LAYOUT';
export const POST_TOGGLE_HELP: POST_TOGGLE_HELP_TYPE =
  'DASHBOARD_POST_PAGE/POST_TOGGLE_HELP';
export const CONFIRM_DELETION: CONFIRM_DELETION_TYPE = 'DASHBOARD_POST_PAGE/CONFIRM_DELETION';
export const CANCEL_DELETION: CANCEL_DELETION_TYPE = 'DASHBOARD_POST_PAGE/CANCEL_DELETION';
